### ISSUE TITLE
Automate publish to npm package

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/vue-ui-components#37]
**Is your feature request related to a problem? Please describe.**
Automate publish to npm package after merging to `master` branch

This includes ensure all the components are added to the index.js file and increase the NPM package version by 1.

**Comment by andrewtpham** [comment]
Message from NPM Support:
```
The hikayaio user doesn't own the dots package, and the dots package does have 2FA enabled for publishes. This package is owned by sindresorhus:

$ npm owner ls dots
sindresorhus <sindresorhus@gmail.com>
```
