### ISSUE TITLE
Search bar: plain and with filter

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/vue-ui-components#63]
This is not in the Element UI library but a custom component.

<img width="771" alt="Screen Shot 2020-05-07 at 2 52 37 PM" src="https://user-images.githubusercontent.com/13760198/81298678-64817300-9075-11ea-87a0-bede2ad86167.png">

Components to build:
## Component 1: Search field
![image](https://user-images.githubusercontent.com/60480501/81251543-846f5300-8ff1-11ea-84e8-f69026bca2a9.png)

## Component 2: Filter
- this will have vertical scroll
![image](https://user-images.githubusercontent.com/60480501/81251564-8fc27e80-8ff1-11ea-9bf8-d22f4f940da3.png)

Use:
Searching users and filtering them in the Workspace setting

**Comment by lupyana** [comment]
@ninetteadhikari the first component, What kind of search are we looking at? Is it an input that will take user to another screen? Or will it provide a dropdown of possible results?

**Comment by lupyana** [comment]
I want to use [Autocomplete ](https://element.eleme.io/#/en-US/component/input#autocomplete-attributes) as the base component, and style it to look like the provided screen. Please advise @ninetteadhikari @andrewtpham

**Comment by ninetteadhikari** [comment]
> @ninetteadhikari the first component, What kind of search are we looking at? Is it an input that will take user to another screen? Or will it provide a dropdown of possible results?

Hi @lupyana this particular one is for searching and filtering items (e.g. users) in a table
![image](https://user-images.githubusercontent.com/13760198/81295946-782ada80-9071-11ea-937f-925a93fbd9d8.png)

But ideally we would want this to be reusable for as a Search component to e.g. search the whole app for something
