### ISSUE TITLE
Input field: remove form tag wrapper

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/vue-ui-components#71]
**Current behavior**
Currently all the input fields are wrapped in form, row, column tags etc.
```
<el-form ref="form" model="form" label-width="120px">
        <el-row :gutter="20">
            <el-col class="grid-content" :span="12">
                <el-input
                    :placeholder="placeholder"
                    v-model="form.input">
                        <slot></slot>
                </el-input>
            </el-col>
        </el-row>
    </el-form>
```

**Expected behavior**
The component will have only the input tag all other tags will be removed
```
<el-input
       :placeholder="placeholder"
        v-model="form.input">
              <slot></slot>
</el-input>
```

**Additional info**
Clean up to be done for all input components:
![image](https://user-images.githubusercontent.com/13760198/80871714-23bcdf00-8cae-11ea-8262-4c2a44bdfbac.png)

**Comment by ninetteadhikari** [comment]
hi @Tanvir-rahman thanks for catching this! I created an issue for this to clean it up :)

**Comment by Tanvir-rahman** [comment]
Before this we need to introduce another component which will expose form only. Ex: el-form. Will you please create another issue for that based on priority level?

**Comment by ninetteadhikari** [comment]
> Hello @ninetteadhikari Before this we need to introduce another component which will expose form only. Ex: el-form. Will you please create another issue for that based on priority level?

@Tanvir-rahman here is the form component issue: https://github.com/hikaya-io/vue-ui-components/issues/76

**Comment by Tanvir-rahman** [comment]
This issue is ready to close now. @ninetteadhikari @andrewtpham
