### ISSUE TITLE
Button: Update button to make them rounder

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/vue-ui-components#72]
**Components to be updated**
Update the current `Buttons` component
```
// Primary

background: #33CCCC;
border: 3px solid #33CCCC;
box-sizing: border-box;
border-radius: 25px;
padding: 11px 33px;

// Danger
background: #FF3333;
border-radius: 25px;
padding: 11px 33px;

// Ghost
border: 1px solid #333333;
box-sizing: border-box;
border-radius: 25px;
padding: 11px 33px;
```
UPDATED
![image](https://user-images.githubusercontent.com/4407063/81236699-12e9d180-8ffe-11ea-82d3-3dacda4f0f7a.png)

**Comment by lupyana** [comment]
@ninetteadhikari what about the other button types i.e success, info and warning? Do you have specific css attributes for them?

**Comment by andrewtpham** [comment]
@lupyana I'm terribly sorry, I forgot to assign myself to this card but I ended up addressing this issue in this PR https://github.com/hikaya-io/vue-ui-components/pull/82/files Maybe you can help review it and I can incorporate any of your changes. Apologies about the mix up 🤦

**Comment by lupyana** [comment]
@andrewtpham thanks for letting know, I will check it out
